version: '3.3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    restart: always
    build: ./web
    image: web
    expose:
      - "8000"
    volumes:
      - code:/web
      - static:/static
      - media:/media
    env_file: .env
    depends_on: 
      - db
    environment:
      DEBUG: 'true'
    command: bash -c "/usr/local/bin/gunicorn ace.wsgi:application -w 2 -b :8000 &&  python manage.py collectstatic --noinput --clear && python manage.py makemigrations && python manage.py migrate"
  nginx:
    restart: always
    build: ./nginx/
    image: nginx
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
    links:
      - web:web

volumes:
  static:
  media:
  pgdata:
  code:
