version: '3.3'

services:
  db:
    image: postgres
    restart: always
    container_name: db
    env_file:
      - db.env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    restart: always
    container_name: web
    build: ./web
    image: web
    expose:
      - "8000"
    volumes:
      - static:/static
      - media:/media
    stdin_open: true
    tty: true
    depends_on: 
      - db
    env_file:
      - ./web.env.dev
    command: bash -c "python manage.py collectstatic --noinput && python manage.py makemigrations --noinput && python manage.py migrate --noinput && /usr/local/bin/gunicorn ace.wsgi:application -w 2 -b :8000"
  nginx:
    restart: always
    build: ./nginx/
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static
      - media:/media
    links:
      - web:web

volumes:
  static:
  media:
  pgdata:

