version: '3.3'

services:
  db:
    image: postgres
    restart: always
    container_name: db
    env_file:
      - db.env
    volumes:
      - ./prod_storage/pgdb:/var/lib/postgresql/data
  web:
    restart: always
    build: ./web
    image: web
    container_name: web
    expose:
      - "8000"
    volumes:
      - ./web:/web
      - static:/static
      - ./prod_storage/media:/media
    stdin_open: true
    tty: true
    depends_on: 
      - db
    env_file:
      - web.env
    command: bash -c "python manage.py collectstatic --noinput && python manage.py makemigrations --noinput && python manage.py migrate --noinput && /usr/local/bin/gunicorn ace.wsgi:application -w 2 -b :8000"
  nginx:
    image: linuxserver/letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - static:/static
      - ./prod_storage/media:/media
      - ./nginx-prod/config:/config
      - ./nginx-prod/config/nginx.conf:/config/nginx/site-confs/default
      - ./nginx-prod/config/ssl.conf:/config/nginx/ssl.conf
    container_name: nginx
    restart: unless-stopped
    links:
      - web:web
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - URL=concordia-ace.ca
      - SUBDOMAINS=www,
      - VALIDATION=http
      - STAGING=true #optional

volumes:
  static: