# Generated by Django 3.0 on 2020-04-11 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('joblistings', '0001_initial'),
        ('jobapplications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOpenToPublic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Candidate')),
                ('job', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='joblistings.Job')),
                ('jobApplication', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobapplications.JobApplication')),
            ],
        ),
        migrations.CreateModel(
            name='MatchingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_matching_to_employer', models.BooleanField(default=True)),
                ('open_matching_to_candidate', models.BooleanField(default=False)),
                ('matchingInProgress', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matches', models.ManyToManyField(to='jobmatchings.Match')),
            ],
        ),
    ]
