# Generated by Django 3.0 on 2020-04-11 03:38

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('ANY', 'Any Category'), ('E_Aero_Mech', 'GCS Engineering - Aerospace & Mechanical'), ('E_Elec', 'GCS Engineering - Electrical'), ('E_Ind', 'GCS Engineering - Industrial'), ('E_QS', 'GCS Engineering - Quality System'), ('E_Soft', 'GCS Engineering and Computer Science - Computer, Information Security & Software'), ('E_Other', 'GCS Engineering - Other'), ('F_A_Design', 'Fine Arts - Computational Arts & Design'), ('J_Acc_Fin', 'JMSB - Accounting & Finance'), ('J_HR_Mar', 'JMSB - HR & Marketing'), ('J_Bus', 'JMSB - Business Administration'), ('J_Man', 'JMSB - Management & Supply Chain Operation Management'), ('J_Other', 'JMSB - Other'), ('A_Acc', 'Arts and Science - Actuarial Mathematics & Finance'), ('A_Econ', 'Arts and Science - Economics'), ('A_Math_Phy', 'Arts and Science - Mathematics & Physics'), ('A_Pol', 'Arts and Science - Political Science'), ('A_BIO_CHEM', 'Arts and Science - Biology & Chemistry'), ('A_Jou', 'Arts and Science - Journalism'), ('A_Tr', 'Arts and Science - Translation'), ('A_Other', 'Arts and Science - Other')], default='Any', max_length=40)),
                ('salaryRange', models.CharField(default='N/A', max_length=40)),
                ('vacancy', models.IntegerField(default=0, null=True)),
                ('filled', models.IntegerField(default=0, null=True)),
                ('startDate', models.CharField(default='', max_length=40)),
                ('expirationDate', models.CharField(default='', max_length=40)),
                ('duration', models.CharField(default='', max_length=40)),
                ('description', tinymce.models.HTMLField(default='', max_length=10000)),
                ('responsabilities', tinymce.models.HTMLField(default='', max_length=10000)),
                ('requirements', tinymce.models.HTMLField(default='', max_length=10000)),
                ('status', models.CharField(choices=[('Pending Review', 'Pending Coop Review'), ('Not Approved', 'Not Approved'), ('Approved', 'Approved'), ('Interviewing', 'Interviewing'), ('Filled', 'Filled'), ('Partially Filled', 'Partially Filled'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('country', models.CharField(choices=[('None', 'Country'), ('CA', 'Canada'), ('US', 'USA'), ('Other-Europe', 'Other- Europe'), ('Other-Asia', 'Other- Asia'), ('Other', 'Other')], default='Canada', max_length=40)),
                ('location', models.CharField(default='Montreal', max_length=40)),
                ('postcode', models.CharField(default='', max_length=40)),
                ('yourLocation', models.CharField(default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('jobAccessPermission', models.ManyToManyField(to='accounts.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='JobPDFDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionFile', models.FileField(default='', upload_to='company/jobDescription.')),
                ('job', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='joblistings.Job')),
            ],
        ),
    ]
